version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./build:/usr/share/nginx/html:ro
    depends_on:
      - react-app
